ci(native): Add some tests to profile script
This commit adds a basic test of the profile shell script to the native workflow.
The new test uses 'timeout' command to validate whether the profile script boots
and starts to render the scene. It only tests the 'release' and 'debug' modes
of the script for now.
The goal is to detect if changes to the profile script breaks it or not.

diff --git a/.github/workflows/native.yml b/.github/workflows/native.yml
--- a/.github/workflows/native.yml
+++ b/.github/workflows/native.yml
@@ -188,6 +188,21 @@ jobs:
         ls -la ./app/src/androidTest/resources/CornellBox/CornellBox-Water.cam;
         LD_LIBRARY_PATH=$(find ~/.conan -iname "libgtest.so" | grep -iv "build" | xargs ls -t | head -1 | xargs dirname) ./build_${{ matrix.type }}/bin/UnitTests* --gtest_filter=*Engine*;
 
+    - name: Test profile script ${{ matrix.type }}
+      timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
+      if: success() && !startsWith(matrix.os, 'macos')
+      working-directory: .
+      run: |
+        set +e;
+        QT_QPA_PLATFORM='offscreen' timeout 4 sh ./scripts/profile.sh "${{ matrix.type }}" 100;
+        returnValue="$?";
+        set -e;
+        # shellcheck disable=SC1091
+        . scripts/test/utils.sh && assertEqual '124' "${returnValue}" "test profile script: ${{ matrix.type }}";
+        if [ "${returnValue}" != '124' ]; then
+          exit "${returnValue}"; # Exit with error if test failed.
+        fi
+
     - name: Generate code coverage
       timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
       if: success() && startsWith(matrix.os, 'ubuntu') && matrix.type == 'debug' && startsWith(matrix.compiler, 'g++')
diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -236,3 +236,19 @@ jobs:
         ls -la ./app/src/androidTest/resources/CornellBox/CornellBox-Water.mtl;
         ls -la ./app/src/androidTest/resources/CornellBox/CornellBox-Water.cam;
         ./build_${{ matrix.type }}/bin/Debug/UnitTests* --gtest_filter=*Engine*;
+
+    - name: Test profile script ${{ matrix.type }}
+      timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
+      if: success()
+      working-directory: .
+      shell: sh
+      run: |
+        set +e;
+        QT_QPA_PLATFORM='offscreen' timeout 4 sh ./scripts/profile.sh "${{ matrix.type }}" 100;
+        returnValue="$?";
+        set -e;
+        # shellcheck disable=SC1091
+        . scripts/test/utils.sh && assertEqual '124' "${returnValue}" "test profile script: ${{ matrix.type }}";
+        if [ "${returnValue}" != '124' ]; then
+          exit "${returnValue}"; # Exit with error if test failed.
+        fi
